const mongoose = require('mongoose');

const elementToolsSchema = new mongoose.Schema({
  plus: { type: String, required: true },
  minus: { type: String, required: true },
  plusMinus: {type: String, required: true},
  multiply: { type: String, required: true },
  divide: { type: String, required: true },
  equal: { type: String, required: true },
  lessThan: { type: String, required: true },
  zero: { type: String, required: true },
  one: { type: String, required: true },
  two: { type: String, required: true },
  three: { type: String, required: true },
  four: { type: String, required: true },
  five: { type: String, required: true },
  six: { type: String, required: true },
  seven: { type: String, required: true },
  eight: { type: String, required: true },
  ten: { type: String, required: true },
  power2: { type: String, required: true },
  power3: { type: String, required: true },
  powerN: { type: String, required: true },
  squareRoot: { type: String, required: true },
  x: { type: String, required: true },
  a: { type: String, required: true },
  b: { type: String, required: true },
  c: { type: String, required: true },
  n: { type: String, required: true },
  elementOf: { type: String, required: true },
  realNumbers: { type: String, required: true },
  triangle: { type: String, required: true },
  angle: { type: String, required: true },
  sigma: { type: String, required: true },
  integral: { type: String, required: true },
  limit: { type: String, required: true },
  infinity: { type: String, required: true },
  ellipsis: { type: String, required: true },
  absoluteValue: { type: String, required: true },
  bracket: { type: String, required: true },
  closeBracket: { type: String, required: true },
  squareBracketOpen: { type: String, required: true },
  squareBracketClose: { type: String, required: true },
  subscript0: { type: String, required: true },
  subscript1: { type: String, required: true },
  subscript2: { type: String, required: true },
  subscript3: { type: String, required: true },
  subscript4: { type: String, required: true },
  subscript5: { type: String, required: true },
  subscript6: { type: String, required: true },
  subscript7: { type: String, required: true },
  subscript8: { type: String, required: true },
  subscript9: { type: String, required: true },
  implies: { type: String, required: true },
  therefore: { type: String, required: true }
});

const ElementToolModel = mongoose.model('ElementTool', elementToolsSchema);

module.exports = ElementToolModel;
